bitscale.c: ensure SCORE2 macro expands properly
Handles warning from Oracle Parfait 11.2 static analyzer:

Error: Misleading macro
   Misleading macro [misleading-macro]:
      misleading evaluation of '/' operator in expansion of macro SCORE2 due to missing parentheses
        at line 299 of src/bitmap/bitscale.c.
        '/' operator has lower precedence than '/' operator inside macro body at line 438
        low precedence '/' operator is hidden by expansion of macro argument m at line 299
   Misleading macro [misleading-macro]:
      misleading evaluation of '/' operator in expansion of macro SCORE2 due to missing parentheses
        at line 299 of src/bitmap/bitscale.c.
        binary '*' operator has lower precedence than '/' operator inside macro body at line 440
        low precedence binary '*' operator is hidden by expansion of macro argument m at line 299

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>